Feature de analise de limite para clientes
Guirollzing/Low-Bank pull request #1
Opened 2023-02-08 00:46 UTC by felipebaltazar

## Alterações

- Criado novo form para analise de limite
- Criada lógica para analise de limite
- Alterada a home para iniciar analise de limite

## Telas alteradas

![image](https://user-images.githubusercontent.com/19656249/217399801-61c7aaeb-550a-456f-b6a4-44dd590055dd.png)
![image](https://user-images.githubusercontent.com/19656249/217399829-94bfec0f-a3f5-48ea-b00e-a634e8dd58f0.png)

2023-02-08 00:50 UTC, felipebaltazar commented on LowBank.Windows/Presentation/Home.Designer.cs
> +            this.accountTextbox.Size = new System.Drawing.Size(217, 25);
Não é legal alterar o tamanho do textbox, desfaz ai

2023-02-08 23:50 UTC, Guirollzing requested changes
Corrigir o bug em que o limite do cheque não se soma.

2023-02-09 00:01 UTC, felipebaltazar commented on LowBank.Windows/Presentation/LimitAnalysis.cs
> +                _customer.Account.Limit = result;
Ta sobreescrevendo o limite anterior

2023-02-09 00:18 UTC, felipebaltazar commented
> Corrigir o bug em que o limite do cheque não se soma.

@Guirollzing ajustei o bug e refatorei o codigo, consegue revisar novamente?

2023-02-09 00:18 UTC, felipebaltazar commented on LowBank.Windows/Presentation/LimitAnalysis.cs
> +                _customer.Account.Limit = result;
Resolvido!

2023-02-09 00:19 UTC, Guirollzing approved these changes

2023-02-09 00:20 UTC, merged