Criado a base do API
Guirollzing/Low-Bank pull request #2
Opened 2023-02-09 17:32 UTC by Guirollzing

2023-02-12 19:22 UTC, felipebaltazar requested changes

2023-02-12 19:22 UTC, felipebaltazar commented on LowBank.Api/Controllers/AccountController.cs
> +    public class AccountController : ControllerBase
Acho que ja vale criar o `CustomerController`  para tratar consultas relacionadas ao cliente

2023-02-14 17:08 UTC, Guirollzing commented on LowBank.Api/Controllers/AccountController.cs
> +    public class AccountController : ControllerBase
Feito!

2023-02-14 17:10 UTC, Guirollzing reviewed
Criado o CustomerController e o Customer.

2023-02-19 03:22 UTC, felipebaltazar approved these changes

2023-02-19 03:22 UTC, felipebaltazar approved these changes

2023-02-23 23:21 UTC, merged